### PR TITLE
Update zh_TW.po

### PR DESCRIPTION
**Pull request by olivertzeng**

### CODE REVIEW

**Comment by Aryan20** [comment]
Hey! Thanks for the work. The link is dropped in the last translation. Is there a reason for it?

**Comment by olivertzeng** [comment]
Because the surrounding text doesn't work in my computer image

**Comment by Aryan20** [comment]
Hmm, it is because of some translation mess up. If you see the link doesn't have a closing </a> anchor tag, hence it got rendered badly.
I'm attaching how it looks on my computer. Can you please fix it accordingly?
Thanks.
image

**Comment by olivertzeng** [comment]
ok

**Comment by olivertzeng** [comment]
> Hmm, it is because of some translation mess up. If you see the link doesn't have a closing anchor tag, hence it got rendered badly. I'm attaching how it looks on my computer. Can you please fix it accordingly? Thanks. image

**Comment by Aryan20** [comment]
Hey! It will still cause issues. The translation is missing the tags 
`"<span size=\"small\">This program comes with absolutely no warranty.\n"
"See the <a href=\"https://gnu.org/licenses/old-licenses/gpl-2.0.html\">GNU "
"General Public License, version 2 or later</a> for details.</span>"`

As you can see, it has multiple tags like `span` and `a` as your translation is missing them, it will break the UI. I recommend you to take it fresh from pot and re-translate this specific part. The strings that need translation would be - `This program comes with absolutely no warranty.`, `See the`, `version 2 or later` and `for details.`

**Comment by olivertzeng** [comment]
Oh tbh that only that part of the text was just off the Internet, I’ll try translating myself, thanks!

**Comment by Aryan20** [comment]
Hey! The translation pot is updated to prevent the links from breaking now :)

**Comment by olivertzeng** [comment]
thanks, do i need to do something else?

**Comment by Aryan20** [comment]
Yeah, just update the PO file on top of latest POT and it should be good :)

**Comment by olivertzeng** [comment]
Thanks! Still have work to do rn so maybe tomorrow(I'm GMT+8 and I usually start using my computer at 7)

**Comment by Aryan20** [comment]
Sure, no issues. Thanks!

**Comment by Aryan20** [comment]
Stale PR. Feel free to reopen when files are updated. Thanks!

**Comment by olivertzeng** [comment]
> Stale PR. Feel free to reopen when files are updated. Thanks!

Unfortunately, I'm using KDE. Thanks anyway!

**Pull request closed without merging**
